### ISSUE TITLE
Wakfu client sources

### ISSUE THREAD

**Issue by hussein-aitlahcen** [WakBox/WakBox-Evolution#1]
Salut, si tu veux avancer plus rapidement, voici le lien vers les sources du client wakfu de 2015, tu peux y obtenir d'importantes informations concernant les packets par exemple [LIEN](https://github.com/hussein-aitlahcen/wakfu-src/tree/master/com/ankamagames/wakfu/client/network/protocol/message)

Quand bien même ces sources ne sont plus valides, elles reste néanmoins très précieuses pour reverse le protocole d'aujourd'hui.

**Comment by KevinSupertramp** [comment]
Hello, ouais cool, je les avais déjà, merci bien!
Ca aide vraiment beaucoup oui, même pour tout ce qui est lecture des fichiers du jeu.

Thanks!
