### ISSUE TITLE
Game protocol

### ISSUE THREAD

**Issue by jac3km4** [WakBox/WakBox-Evolution#2]
Hello!
If you're interested in reversing the game's protocol I am able to infer the structure of all messages via Java bytecode analysis. It's performed by simply finding all subclasses of a proper interface/abstract class. I can find out what data structures are contained in each message. You can see an example implementation of this technique [here](https://bitbucket.org/jac3km4/wakfu-restructure/). This way you can always see the up-to-date structures.

**Comment by KevinSupertramp** [comment]
Hi there!
Waow this is really cool! Thanks a lot of sharing this with us.
If you want to be more involved, feel free to join us on Discord: https://discord.gg/M2QYJ6P .

Thanks again!
